"""Set is_admin nullable=False

Revision ID: 225681b7a511
Revises: 3c42f0111d52
Create Date: 2025-12-03 15:42:53.493020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225681b7a511'
down_revision = '3c42f0111d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
